### ISSUE TITLE
Errors inside inline templates can disappear as a result of some modifications

### ISSUE THREAD

**Issue by ddrone** [dart-lang/angular2-dart-analyzer#33] opened 2016-11-04 14:47 UTC
GIF explains it all
![out2-1](https://cloud.githubusercontent.com/assets/864538/20009769/9d71510e-a29d-11e6-861b-ccb328ef92ea.gif)

**Comment by MichaelRFairhurst** [comment] 2016-11-10 22:34
I think this might be caused by this error which I just saw right before seeing html analysis stop refreshing.

```Task failed: ResolveHtmlTemplateTask for template /home/mfairhurst/dart/example_ng2_project/lib/blah_example_component.html of View(classElement=class ExampleComponent, component=Component(ExampleComponent selector=blah-blah inputs=[]), directives=[])","stackTrace":"Unexpected exception while performing ResolveHtmlTemplateTask for template /home/mfairhurst/dart/example_ng2_project/lib/blah_example_component.html of View(classElement=class ExampleComponent, component=Component(ExampleComponent selector=blah-blah inputs=[]), directives=[])\n#0      AnalysisTask._safelyPerform (package:analyzer/task/model.dart:351)\n#1      AnalysisTask.perform (package:analyzer/task/model.dart:238)\n#2      AnalysisDriver.performWorkItem (package:analyzer/src/task/driver.dart:284)\n#3      AnalysisDriver.performAnalysisTask (package:analyzer/src/task/driver.dart:255)\n#4      AnalysisContextImpl.performAnalysisTask.<anonymous closure> (package:analyzer/src/context/context.dart:1185)\n#5      _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:212)\n#6      AnalysisContextImpl.performAnalysisTask (package:analyzer/src/context/context.dart:1183)\n#7      PerformAnalysisOperation.perform (package:analysis_server/src/operation/operation_analysis.dart:362)\n#8      AnalysisServer.performOperation (package:analysis_server/src/analysis_server.dart:911)\n#9      Future.Future.<anonymous closure> (dart:async/future.dart:118)\n#10     _rootRun (dart:async/zone.dart:1146)\n#11     _CustomZone.run (dart:async/zone.dart:1026)\n#12     _CustomZone.runGuarded (dart:async/zone.dart:924)\n#13     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:951)\n#14     _rootRun (dart:async/zone.dart:1150)\n#15     _CustomZone.run (dart:async/zone.dart:1026)\n#16     _CustomZone.runGuarded (dart:async/zone.dart:924)\n#17     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:951)\n#18     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:16)\n#19     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:385)\n#20     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:414)\n#21     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)\n\nCaused by type 'ParseErrorToken' is not a subtype of type 'StartTagToken' in type cast where\n  ParseErrorToken is from package:html/src/token.dart\n  StartTagToken is from package:html/src/token.dart\n\n#0      Object._as (dart:core-patch/object_patch.dart:74)\n#1      Node._ensureAttributeSpans (package:html/dom.dart:286)\n#2      Node.attributeSpans (package:html/dom.dart:173)\n#3      HtmlTreeConverter._convertAttributes.<anonymous closure> (package:angular2_analyzer_plugin/src/resolver.dart:278)\n#4      _HashVMBase&MapMixin&&_LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:351)\n#5      HtmlTreeConverter._convertAttributes (package:angular2_analyzer_plugin/src/resolver.dart:275)\n#6      HtmlTreeConverter.convert (package:angular2_analyzer_plugin/src/resolver.dart:241)\n#7      HtmlTreeConverter._convertChildren (package:angular2_analyzer_plugin/src/resolver.dart:324)\n#8      HtmlTreeConverter.convert (package:angular2_analyzer_plugin/src/resolver.dart:261)\n#9      HtmlTreeConverter._convertChildren (package:angular2_analyzer_plugin/src/resolver.dart:324)\n#10     HtmlTreeConverter.convert (package:angular2_analyzer_plugin/src/resolver.dart:261)\n#11     HtmlTreeConverter._convertChildren (package:angular2_analyzer_plugin/src/resolver.dart:324)\n#12     HtmlTreeConverter.convert (package:angular2_analyzer_plugin/src/resolver.dart:261)\n#13     TemplateResolver.resolve (package:angular2_analyzer_plugin/src/resolver.dart:431)\n#14     HtmlTemplateResolver.resolve (package:angular2_analyzer_plugin/src/resolver.dart:232)\n#15     ResolveHtmlTemplateTask.internalPerform (package:angular2_analyzer_plugin/src/tasks.dart:1073)\n#16     AnalysisTask._safelyPerform (package:analyzer/task/model.dart:339)\n#17     AnalysisTask.perform (package:analyzer/task/model.dart:238)\n#18     AnalysisDriver.performWorkItem (package:analyzer/src/task/driver.dart:284)\n#19     AnalysisDriver.performAnalysisTask (package:analyzer/src/task/driver.dart:255)\n#20     AnalysisContextImpl.performAnalysisTask.<anonymous closure> (package:analyzer/src/context/context.dart:1185)\n#21     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:212)\n#22     AnalysisContextImpl.performAnalysisTask (package:analyzer/src/context/context.dart:1183)\n#23     PerformAnalysisOperation.perform (package:analysis_server/src/operation/operation_analysis.dart:362)\n#24     AnalysisServer.performOperation (package:analysis_server/src/analysis_server.dart:911)\n#25     Future.Future.<anonymous closure> (dart:async/future.dart:118)\n#26     _rootRun (dart:async/zone.dart:1146)\n#27     _CustomZone.run (dart:async/zone.dart:1026)\n#28     _CustomZone.runGuarded (dart:async/zone.dart:924)\n#29     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:951)\n#30     _rootRun (dart:async/zone.dart:1150)\n#31     _CustomZone.run (dart:async/zone.dart:1026)\n#32     _CustomZone.runGuarded (dart:async/zone.dart:924)\n#33     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:951)\n#34     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:16)\n#35     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:385)\n#36     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:414)\n#37     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)\n\n"}}```

**Comment by MichaelRFairhurst** [comment] 2016-11-10 23:35
Catching this error seems to work, but I think I will try to fix it in the dart html package. The problem essentially comes down to that package creating a map of attributes and values, but throwing an exception when you try to get their source ranges. Seems like their problem more than ours though I can commit my temp fix if that turns out to be best.

**Comment by MichaelRFairhurst** [comment] 2016-11-10 23:37
quick solution in the referenced commit here

**Comment by MichaelRFairhurst** [comment] 2016-11-12 00:36
Resolving this.

**Closed by MichaelRFairhurst** 2016-11-12 00:36 UTC
Labels: bug, p1

**Comment by ddrone** [comment] 2016-11-14 13:18
Thanks for fixing this!
